# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/A7-50t Constraint Files/Nexys-A7-50T-Master.xdc

# Block Designs: bd/embsys/embsys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys || ORIG_REF_NAME==embsys} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_1/embsys_microblaze_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_1 || ORIG_REF_NAME==embsys_microblaze_0_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_nexys4IO_0_1/embsys_nexys4IO_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_nexys4IO_0_1 || ORIG_REF_NAME==embsys_nexys4IO_0_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_PmodOLEDrgb_0_1/embsys_PmodOLEDrgb_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_PmodOLEDrgb_0_1 || ORIG_REF_NAME==embsys_PmodOLEDrgb_0_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_0_1/embsys_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_0_1 || ORIG_REF_NAME==embsys_axi_gpio_0_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_timer_0_1/embsys_axi_timer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_axi_timer_0_1 || ORIG_REF_NAME==embsys_axi_timer_0_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_fit_timer_0_1/embsys_fit_timer_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_fit_timer_0_1 || ORIG_REF_NAME==embsys_fit_timer_0_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_uartlite_0_1/embsys_axi_uartlite_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_axi_uartlite_0_1 || ORIG_REF_NAME==embsys_axi_uartlite_0_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_axi_periph_1/embsys_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_periph_1 || ORIG_REF_NAME==embsys_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_axi_intc_1/embsys_microblaze_0_axi_intc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_axi_intc_1 || ORIG_REF_NAME==embsys_microblaze_0_axi_intc_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_microblaze_0_xlconcat_1/embsys_microblaze_0_xlconcat_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_microblaze_0_xlconcat_1 || ORIG_REF_NAME==embsys_microblaze_0_xlconcat_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_mdm_1_1/embsys_mdm_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_mdm_1_1 || ORIG_REF_NAME==embsys_mdm_1_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_clk_wiz_1_1/embsys_clk_wiz_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_clk_wiz_1_1 || ORIG_REF_NAME==embsys_clk_wiz_1_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_rst_clk_wiz_1_100M_1/embsys_rst_clk_wiz_1_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_rst_clk_wiz_1_100M_1 || ORIG_REF_NAME==embsys_rst_clk_wiz_1_100M_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_xbar_1/embsys_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_xbar_1 || ORIG_REF_NAME==embsys_xbar_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_dlmb_v10_1/embsys_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_dlmb_v10_1 || ORIG_REF_NAME==embsys_dlmb_v10_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_ilmb_v10_1/embsys_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_ilmb_v10_1 || ORIG_REF_NAME==embsys_ilmb_v10_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_dlmb_bram_if_cntlr_1/embsys_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==embsys_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_ilmb_bram_if_cntlr_1/embsys_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==embsys_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_lmb_bram_1/embsys_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_lmb_bram_1 || ORIG_REF_NAME==embsys_lmb_bram_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_PmodENC_0_1/embsys_PmodENC_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_PmodENC_0_1 || ORIG_REF_NAME==embsys_PmodENC_0_1} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_gpio_1_0/embsys_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_axi_gpio_1_0 || ORIG_REF_NAME==embsys_axi_gpio_1_0} -quiet] -quiet

# IP: bd/embsys/ip/embsys_axi_timebase_wdt_0_0/embsys_axi_timebase_wdt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==embsys_axi_timebase_wdt_0_0 || ORIG_REF_NAME==embsys_axi_timebase_wdt_0_0} -quiet] -quiet

# XDC: bd/embsys/embsys_ooc.xdc
