# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param tcl.collectionResultDisplayLimit 0
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a50tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/ME/Vivado_Projects/project_2/project_2.cache/wt [current_project]
set_property parent.project_path C:/Users/ME/Vivado_Projects/project_2/project_2.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  {c:/Users/ME/OneDrive/Documents/School/PSU/Spring2020/ECE544/Projects/Project Source Files/ece544ip-library-master}
  c:/Users/ME/OneDrive/Documents/School/PSU/Spring2020/ECE544/Projects/Project2/pmodhb3/pmod_hb3_1.0
  {c:/Users/ME/OneDrive/Documents/School/PSU/Spring2020/ECE544/Projects/Project Source Files/vivado-library-v2019.1-1}
} [current_project]
set_property ip_output_repo c:/Users/ME/Vivado_Projects/project_2/project_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/imports/hardware/nexysA7fpga.v
add_files C:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/embsys.bd
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_1/embsys_microblaze_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_1/embsys_microblaze_0_1_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_1/embsys_microblaze_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_quad_spi_0_0/PmodOLEDrgb_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_axi_gpio_0_1/PmodOLEDrgb_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_pmod_bridge_0_0/PmodOLEDrgb_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_1/ip/PmodOLEDrgb_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodOLEDrgb_0_1/embsys_PmodOLEDrgb_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_0_1/embsys_axi_gpio_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_0_1/embsys_axi_gpio_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_0_1/embsys_axi_gpio_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_axi_timer_0_1/embsys_axi_timer_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_axi_timer_0_1/embsys_axi_timer_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_fit_timer_0_1/embsys_fit_timer_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_axi_uartlite_0_1/embsys_axi_uartlite_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_axi_uartlite_0_1/embsys_axi_uartlite_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_axi_uartlite_0_1/embsys_axi_uartlite_0_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_1/embsys_microblaze_0_axi_intc_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_1/embsys_microblaze_0_axi_intc_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_microblaze_0_axi_intc_1/embsys_microblaze_0_axi_intc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_mdm_1_1/embsys_mdm_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_mdm_1_1/embsys_mdm_1_1_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_mdm_1_1/embsys_mdm_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_clk_wiz_1_1/embsys_clk_wiz_1_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_clk_wiz_1_1/embsys_clk_wiz_1_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_clk_wiz_1_1/embsys_clk_wiz_1_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_rst_clk_wiz_1_100M_1/embsys_rst_clk_wiz_1_100M_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_rst_clk_wiz_1_100M_1/embsys_rst_clk_wiz_1_100M_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_rst_clk_wiz_1_100M_1/embsys_rst_clk_wiz_1_100M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_xbar_1/embsys_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_dlmb_v10_1/embsys_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_dlmb_v10_1/embsys_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_ilmb_v10_1/embsys_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_ilmb_v10_1/embsys_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_dlmb_bram_if_cntlr_1/embsys_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_ilmb_bram_if_cntlr_1/embsys_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_lmb_bram_1/embsys_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_1/src/PmodENC_pmod_bridge_0_0/PmodENC_pmod_bridge_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_1/src/PmodENC_pmod_bridge_0_0/src/pmod_concat_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_1/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_1/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_1/src/PmodENC_axi_gpio_0_0/PmodENC_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_1/embsys_PmodENC_0_1_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_PmodENC_0_1/src/PmodENC_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_1_0/embsys_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_1_0/embsys_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_axi_gpio_1_0/embsys_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_axi_timebase_wdt_0_0/embsys_axi_timebase_wdt_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_axi_timebase_wdt_0_0/embsys_axi_timebase_wdt_0_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_ila_0_0/ila_v6_2/constraints/ila_impl.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/ip/embsys_ila_0_0/embsys_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/ME/Vivado_Projects/project_2/project_2.srcs/sources_1/bd/embsys/embsys_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/ME/Vivado_Projects/project_2/project_2.srcs/constrs_1/imports/A7-50t Constraint Files/Nexys-A7-50T-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/ME/Vivado_Projects/project_2/project_2.srcs/constrs_1/imports/A7-50t Constraint Files/Nexys-A7-50T-Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top nexysA7fpga -part xc7a50tcsg324-1 -fanout_limit 1000 -directive FewerCarryChains -retiming


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef nexysA7fpga.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file nexysA7fpga_utilization_synth.rpt -pb nexysA7fpga_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
